name: CI 

on:
# trigger workflow on  push request
  push:
    branches: [master]

  workflow_dispatch:  
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      
    - uses: actions/checkout@v3
      name: Build
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      
      
      
